name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- master
- dotliquid
- refs/heads/dotliquid
pr:
- dotliquid
- main
- templates/*

variables:
  solution: '**/*.sln'
  unitTestProjects: "**/*UnitTests/*.csproj"
  publishProject: "**/*Tool/*.csproj"
  functionalTests: "**/*FunctionalTests/*.csproj"
  buildConfiguration: 'Release'
  major: 4
  minor: 5
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}',variables['major'],variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)

stages:
- stage: Build
  pool:
      vmImage: 'windows-latest'
  jobs:
  - job: Build
    steps:
    - script: echo $(version)

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: build
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration) -p:Version=$(version)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet test'
      inputs:
        command: test
        projects: '$(unitTestProjects)'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
        nobuild: true

    - task: DotNetCoreCLI@2
      displayName: 'publish bin'
      inputs:
        command: 'publish'
        projects: '$(publishProject)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.SourcesDirectory)/bin/publish'
        nobuild: true
        publishWebProjects: false
        zipAfterPublish: false

    - task: DotNetCoreCLI@2
      displayName: 'publish github release bin'
      inputs:
        command: 'publish'
        projects: '$(publishProject)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/bin'
        nobuild: true
        publishWebProjects: false
        zipAfterPublish: true

    - task: DotNetCoreCLI@2
      displayName: 'publish functional tests'
      inputs:
        command: 'publish'
        projects: '$(functionalTests)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/functionalTests'
        nobuild: true
        publishWebProjects: false
        zipAfterPublish: false

    - task: PowerShell@2
      displayName: 'inject template version'
      inputs:
        targetType: 'inline'
        script: |
          $targetPath = '$(Build.SourcesDirectory)/data/Templates/Hl7v2/Resource/_Provenance.liquid'
          (Get-Content $targetPath).replace('TEMPLATE_VERSION_PLACEHOLDER', '$(major).$(minor).$(patch)') | Set-Content $targetPath

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/data/Templates/Hl7v2'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.SourcesDirectory)/data/Templates/Hl7v2DefaultTemplates.tar.gz'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/data/Templates/Ccda'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.SourcesDirectory)/data/Templates/CcdaDefaultTemplates.tar.gz'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/data/Templates/Json'
        includeRootFolder: false
        archiveType: 'tar'
        tarCompression: 'gz'
        archiveFile: '$(Build.SourcesDirectory)/data/Templates/JsonDefaultTemplates.tar.gz'

    - task: CopyFiles@2
      displayName: 'copy DefaultTemplates to artifacts'
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/data'
        targetFolder: '$(Build.ArtifactStagingDirectory)/data'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack nugets'
      inputs:
        command: custom
        custom: pack
        arguments: >
          --configuration $(buildConfiguration)
          --output $(Build.BinariesDirectory)/nupkgs
          --no-build
          -p:NuspecProperties="version=$(version)"
    
    - task: PublishBuildArtifacts@1
      displayName: 'publish nuget artifacts'
      inputs:
        pathToPublish: '$(Build.BinariesDirectory)/nupkgs'
        artifactName: 'nuget'
        publishLocation: 'container'     
    
    - task: PublishBuildArtifacts@1
      displayName: 'publish artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'FhirConverterBuild'

- stage: FunctionalTests
  jobs:
  - job: Windows_Functional_Test
    pool:
        vmImage: 'windows-latest'
    continueOnError: false
    steps:
    - checkout: none #skip checking out the default repository resource
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Artifacts'
      inputs:
        artifactName: FhirConverterBuild
        downloadPath: $(System.DefaultWorkingDirectory)
    - script: |
        docker pull wusongrui/registry-windows:2.7.1
        docker run --rm -d -p 5000:5000 --name registry wusongrui/registry-windows:2.7.1
      displayName: start registry

    - script: |
        dotnet test FhirConverterBuild/**/*FunctionalTests.dll
      displayName: Functional Tests
    - task: Docker@2
      displayName: stop registry
      condition: succeededOrFailed()
      inputs:
        command: stop
        container: registry